### ISSUE TITLE
Accounthistory in Whale not working

### ISSUE THREAD

**Issue by Stonygan** [DeFiCh/jellyfishsdk#1610]
What are the requirements to get this up and running?

https://ocean.defichain.com/v0/mainnet/address/dQyHdMaCKgJU6XUbo9gQrqSzXWRrFR5QEP/history

Only running docker Node and whale-api give me ClientApiError: 404 - Not Found

**Comment by fuxingloh** [comment]
/area apps

Is `-acindex=1` set on defid? Make sure`-disablewallet=1` isn't enabled either, since your need wallet to access account history.

**Comment by Stonygan** [comment]
> /area apps
> 
> Is `-acindex=1` set on defid? Make sure`-disablewallet=1` isn't enabled either, since your need wallet to access account history.

wallet was disabled, thank you! Working fine now. :roll_eyes:
