### ISSUE TITLE
History API doesn't work if size parameter passed is larger than number of transactions

### ISSUE THREAD

**Issue by jovanjellylabs** [DeFiCh/jellyfishsdk#1731]
#### What happened:
History request returns an error (JSON integer out of range) when size attribute is larger than the number of transactions.

#### What you expected to happen:
Request should return all the available transactions without returning an error.

#### How to reproduce it (as minimally and precisely as possible):
Example request: https://ocean.defichain.com/v0/testnet/address/tf1qd5a34pm8nd6d6yh87npf4ze6fsuu4v5l9dp3hm/history?size=30&next=9278f1f8a34f2a39cf10c85ffb6ee3ee2b5302aa576fad0a9ac62c77a5b9c199-UtxosToAccount-991365

#### Anything else we need to know?:
This behavior makes it virtually impossible to get transactions without knowing the exact number of transactions.

**Comment by fuxingloh** [comment]
/duplicate as this was mentioned in #1701 and fixed in #1710, however, it wasn't deployed on Ocean TestNet yet due to the upcoming hard fork and focus is currently on that now.
