### ISSUE TITLE
`status-api` Implement another monitoring api to track oracle statuses

### ISSUE THREAD

**Issue by nichellekoh** [DeFiCh/jellyfishsdk#1748]
#### What would you like to be added:
Implement another monitoring api within `status-api` for oracle status on top of existing `getOracleStatus` to track the number of available oracle provider per ticker e.g. 4 available out of 6 total 

#### Why is this needed:
This will provide more accurate alerting for us to action on, i.e. if >30% of the oracle providers of each ticker is down.

**Comment by fuxingloh** [comment]
/area apps
/triage accepted

Low priority, reserved as a good first issue for the uninitiated.

**Comment by nichellekoh** [comment]
Oracle status should be at **risk** if the following conditions are met: 
`active oracles = 3 `or `(>25%) of the oracles are inactive`
