### ISSUE TITLE
`DeFiCh/ain:2.11.0` Release Test Plan

### ISSUE THREAD

**Issue by fuxingloh** [DeFiCh/jellyfishsdk#1749]
This issue tracks the Test Plan for a success `2.10.x` and `2.11.x` release.

**Please add more tests as deemed necessarily.** 

### Negative Interest Loan 

/assign @DieHard073055

- [ ] should take a loan with negative interest rate and accrue DUSD
- [ ] should fully pay back a vault with negative interest rate
- [ ] should fully pay back a vault with multiple loans including negative interest rate loan
- [ ] should pay back a vault partially with negative interest rate
- [ ] should pay back a vault partially with multiple loans including negative interest rate loan

### "Loop" Vault Loan & Collateral

/assign @canonbrother 

- [ ] TODO

### v2.11.x Regression/Changes https://github.com/JellyfishSDK/jellyfish/pull/1751

- [ ] TODO

**Comment by DieHard073055** [comment]
@fuxingloh Could you please point me where to start ? I have no context on this. :sweat_smile:

**Comment by fuxingloh** [comment]
@canonbrother do you mind helping by pointing to @DieHard073055 on a few test cases he can follow as an example.

**Comment by DieHard073055** [comment]
In the meantime I am taking a look at [this](https://github.com/JellyfishSDK/jellyfish/blob/7a8c318b4e133bf1b94bc991b64b42e7169a82d8/packages/jellyfish-api-core/__tests__/category/loan/takeLoan.test.ts)

**Comment by fuxingloh** [comment]
@DieHard073055 keep me updated, need this ASAP.

**Comment by DieHard073055** [comment]
@fuxingloh ok! ill prioritise working on this.

**Comment by DieHard073055** [comment]
I followed the test [takeLoan.test.ts](https://github.com/JellyfishSDK/jellyfish/blob/5fb37476fdc6ca37765d945c94cfe5c162f5a515/packages/jellyfish-api-core/__tests__/category/loan/takeLoan.test.ts) .
When I set the interest rate to negative like so
```javascript
    // loan scheme set up
    await alice.rpc.loan.createLoanScheme({
      minColRatio: 200,
      interestRate: new BigNumber(-3),
      id: 'scheme'
    })
```
I got the error `Amount out of range`.
Which is from [defichain source](https://github.com/DeFiCh/ain/blob/master/src/rpc/util.cpp#L80).
Then @canonbrother asked me to check the [defichain test](https://github.com/DeFiCh/ain/blob/3d239f21526c816b36370bceb90d40ab0644b69c/test/functional/feature_negative_loan_interest.py)
Over there the test setup is alot more obvious
```python
        # Create loan scheme
        self.nodes[0].createloanscheme(150, 5, 'LOAN001')
```
The interest rate is set to positive. But the negative interest is set via the `setgov` rpc call
```python
        self.nodes[0].setgov({"ATTRIBUTES":{f'v0/token/{self.idDUSD}/loan_minting_interest':'-5'}})
```
I updated my test to a similar setup.
But had issues with docker, the container stopped
```
❯ npm t packages/jellyfish-api-core/__tests__/category/loan/negativeInterest.test.ts 

> defichain@0.0.0 test
> jest --maxWorkers=100% packages/jellyfish-api-core/__tests__/category/loan/negativeInterest.test.ts

 FAIL  packages/jellyfish-api-core/__tests__/category/loan/negativeInterest.test.ts (43.727 s)
  takeLoan with negative interest success
    ✕ should takeLoan with negative interest and accrue DUSD (41167 ms)

  ● takeLoan with negative interest success › should takeLoan with negative interest and accrue DUSD

    waitForRpc is not ready within given timeout of 40000ms.
      16 |         resolve()
      17 |       } else if (expiredAt < Date.now()) {
    > 18 |         reject(new Error(`${message} is not ready within given timeout of ${timeout}ms.`))
         |                ^
      19 |       } else {      20 |         setTimeout(() => void checkCondition(), interval)
      21 |       }

      at checkCondition (packages/testcontainers/src/utils.ts:18:16)
  ● takeLoan with negative interest success › should takeLoan with negative interest and accrue DUSD
    (HTTP code 304) container already stopped -

      at node_modules/docker-modem/lib/modem.js:324:17
      at getCause (node_modules/docker-modem/lib/modem.js:354:7)
      at Modem.Object.<anonymous>.Modem.buildPayload (node_modules/docker-modem/lib/modem.js:323:5)
      at IncomingMessage.<anonymous> (node_modules/docker-modem/lib/modem.js:295:14)

Test Suites: 1 failed, 1 total
Tests:       1 failed, 1 total
Snapshots:   0 total
Time:        43.762 s
Ran all test suites matching /packages\/jellyfish-api-core\/__tests__\/category\/loan\/negativeInterest.test.ts/i.
```
Currently working out what could be cause for this. Thanks to @canonbrother i manage to get till here.

**Comment by DieHard073055** [comment]
Also @fuxingloh may i have permission to push to jellyfish.
```shell
jellyfish [ DieHard073055/add_negative_interest_rate_tests][$!][📦 v0.0.0][ v16.14.2][☁️  eshan@cakedefi.com]
❯ git push --set-upstream origin DieHard073055/add_negative_interest_rate_tests
ERROR: Permission to JellyfishSDK/jellyfish.git denied to DieHard073055.
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
```

**Comment by Jouzo** [comment]
Test cases on ain for reference :
https://github.com/DeFiCh/ain/blob/master/test/functional/feature_negative_interest.py @DieHard073055 
https://github.com/DeFiCh/ain/blob/master/test/functional/feature_negative_loan_interest.py @DieHard073055 

https://github.com/DeFiCh/ain/blob/master/test/functional/feature_loan_payback_with_collateral.py @canonbrother

**Comment by fuxingloh** [comment]
Close as separate tickets are created to tackle the above:

1. https://github.com/JellyfishSDK/jellyfish/issues/1773
2. https://github.com/JellyfishSDK/jellyfish/issues/1769
3. https://github.com/JellyfishSDK/jellyfish/issues/1764
