### ISSUE TITLE
connect EMFILE ip:port - Local (undefined:undefined)

### ISSUE THREAD

**Issue by sambP** [DeFiCh/jellyfishsdk#1762]
Hi, we are recieving some of these errors when interacting with our rpc cluster (some nodes behind a load balancer). I would guess around 2% of the requests result in this error. The most problematic thing about this is that it is not catchable with a try-catch, it throws an Unhandled Promise Rejection and kills the whole lambda. 

Did you encounter this in the past also? Do you have any tips for us? I have currently no idea how we should handle this.

```
"@defichain/jellyfish-api-jsonrpc": "2.58.0",
import { JsonRpcClient } from '@defichain/jellyfish-api-jsonrpc';
nodes are currently on 2.11.0, but this also happened with 2.10.x
```

```
FetchError: request to http://user:password@ip:port/ failed, reason: connect EMFILE ip:port - Local (undefined:undefined)",
at ClientRequest.<anonymous> (/var/task/node_modules/node-fetch/lib/index.js:1491:11)",
at ClientRequest.emit (node:events:539:35)",
at ClientRequest.emit (node:domain:475:12)",
at Socket.socketErrorListener (node:_http_client:454:9)",
at Socket.emit (node:events:527:28)",
at Socket.emit (node:domain:475:12)",
at emitErrorNT (node:internal/streams/destroy:157:8)",
at emitErrorCloseNT (node:internal/streams/destroy:122:3)",
at processTicksAndRejections (node:internal/process/task_queues:83:21)"
```

**Comment by fuxingloh** [comment]
> Did you encounter this in the past also? Do you have any tips for us? I have currently no idea how we should handle this.

Nope, this is the first time I'm seeing this issue.

**Comment by sambP** [comment]
Okay, I will try to build some reproducible.

**Comment by sambP** [comment]
I executed the RPC requests in parallel, and there seemed to be too many threads for the lambda environment. That's why I couldn't reproduce it locally (higher thread limit). Capping the max amount of parallel threads to 100 solved the problem. Sorry for bothering you, it wasn't really a jellyfish problem.
