### ISSUE TITLE
Ocean API missing DUSD price?

### ISSUE THREAD

**Issue by luzianscherrer** [DeFiCh/jellyfishsdk#1789]
Why is the DUSD price not available from the Ocean API and where would be the recommended place to get it from?

```
$ curl https://ocean.defichain.com/v0/mainnet/prices/DUSD-USD
{}
```

**Comment by fuxingloh** [comment]
/area apps
/apps whale-api

What you're querying is the PRICES TICKER API; it allows you to query the aggregated price data from participating oracles. Given oracle's price ticker are USD currency paired (A/USD, B/USD), **DUSD** is the base denominator with no oracles. It will always be 1/1, regardless of market conditions.

**Comment by luzianscherrer** [comment]
Ok, I got it. Thanks for the clarification!
