### ISSUE TITLE
`DeFiCh/ain` upcoming `3.0.x` Upgrade

### ISSUE THREAD

**Issue by fuxingloh** [DeFiCh/jellyfishsdk#1817]
> This issue tracks the upcoming `3.0.x` upgrade and relevant high-level changes that JellyfishSDK needs to be aware of.

### Externals - @fuxingloh & @infinia-yzl 

These are considered features, and should be added and expanded as such. I will find resources to tackle these.

- [x] #1821
- [x] #1822
- [x] #1820
- [x] #1823

### Internal Changes - @shohamc1

These changes should be tested and reflected on existing tests. Will require help from `DeFiCh/ain` to tackle these. 

- [x] Internal Bug Fixes

**Comment by shohamc1** [comment]
Removed `Block Time Change` as it is no longer planned for the 3.0 release.

**Comment by shohamc1** [comment]
Removed `Commission Fix` and `DEX Fee Automation` as it is no longer planned.
