### ISSUE TITLE
On Chain Governance RPCs

### ISSUE THREAD

**Issue by fuxingloh** [DeFiCh/jellyfishsdk#1821]
Similar to https://github.com/DeFiCh/jellyfish/issues/48 This tracks all the RPC methods and categories being implemented in `jellyfish-api-core`. Please tag update this if you want to work on a feature.

#### What would you like to be added:

...

#### Why is this needed:

---

/triage accepted
/kind feature
/area packages
/priority important-soon

**Comment by fuxingloh** [comment]
/assign @infinia-yzl to manage and assign to BR_Hydra related to upcoming work.

For reference, check out https://github.com/JellyfishSDK/jellyfish/issues/1773, please edit and fill in the issue.
I believe this is already partially completed; if that's the case, we should update the tests to reflect that.

**Comment by delphk** [comment]
hi @fuxingloh can I just clarify - 
1. which branch I should refer to on DeFiCh/ain for this? is it this:  https://github.com/DeFiCh/ain/pull/1441/files#diff-f28965a658faa2c397011023357cef79a9399e919fb215d02433a9cd6dfe4acd

2. in which case, there will be a total of 6 new rpc methods
`creategovcfp`, `creategovvoc`, `votegov`, `listgovvotes`, `getgovproposal` and `listgovproposals`?

3.  which docker image should i use for the tests?

4. i saw that there are existing rpc governance methods in jellyfish here https://github.com/JellyfishSDK/jellyfish/blob/main/packages/jellyfish-api-core/src/category/governance.ts but could not find the corresponding methods in DeFiCh/ain, the tests in jellyfish are also skipped for those. should i replace the code there with the above methods?

**Comment by fuxingloh** [comment]
> 1. which branch I should refer to on DeFiCh/ain for this? is it this:  https://github.com/DeFiCh/ain/pull/1441/files#diff-f28965a658faa2c397011023357cef79a9399e919fb215d02433a9cd6dfe4acd

Yup, but you should also refer to the latest docker image from the branch. See https://github.com/DeFiCh/ain/commits/epic/grandcentral where you get the latest docker image build from https://github.com/DeFiCh/ain/actions/runs/3288806927/jobs/5419586518#step:7:73

> 2. in which case, there will be a total of 6 new rpc methods
>    `creategovcfp`, `creategovvoc`, `votegov`, `listgovvotes`, `getgovproposal` and `listgovproposals`?

Yea, it seems like it.

> 3. which docker image should i use for the tests?

See above.


> 4. i saw that there are existing rpc governance methods in jellyfish here https://github.com/JellyfishSDK/jellyfish/blob/main/packages/jellyfish-api-core/src/category/governance.ts but could not find the corresponding methods in DeFiCh/ain, the tests in jellyfish are also skipped for those. should i replace the code there with the above methods?

Yup. You should replace it; the test was written very long ago but seems largely inaccurate.
