### ISSUE TITLE
Add RenovateBot RegexManager to automate `defid` versions update in @defichain/testcontainer

### ISSUE THREAD

**Issue by fuxingloh** [DeFiCh/jellyfishsdk#1850]
#### What would you like to be added:

As per the title, RenovateBot supports custom Regex Matcher. https://docs.renovatebot.com/configuration-options/#regexmanagers

#### Why is this needed:

Shift left and update docker image earlier. Prevent regression and incompatibility issues earlier in the development workflow.

**Comment by fuxingloh** [comment]
/assign @shohamc1 can you help with this? It's directly related to https://github.com/JellyfishSDK/jellyfish/pull/1841

By automating this, when we merge and release on `DeFiCh/ain` it will automatically create a PR here.

**Comment by shohamc1** [comment]
This does not seem possible on Renovate. The [versioning](https://docs.renovatebot.com/modules/versioning/#regular-expression-versioning) requires some form of semver to tell if a newer version is available, which does not work with our current `master-*` and `HEAD-*` tagging scheme.

**Comment by fuxingloh** [comment]
There is still some merit towards just tracking the semver updates. 

However, I will remove the issue assignment for now for you to work on other things.

**Comment by fuxingloh** [comment]
> There is still some merit towards just tracking the semver updates.
> 
> However, I will remove the issue assignment for now for you to work on other things.

E.g. https://github.com/JellyfishSDK/jellyfish/pull/1879

**Comment by fuxingloh** [comment]
/triage accepted

We should tackle this somehow, having to manually update along side renovatebot is pretty annoying.
