### ISSUE TITLE
`poolpair`: update `getTotalLiquidityUsd` to use `dexPrices` for accurate results

### ISSUE THREAD

**Issue by thedoublejay** [DeFiCh/jellyfishsdk#1852]
#### What would you like to be added:
Due to introduction of `csETH-dETH`, we now have a pair that is not stablecoin or DFI based. The function to calculate `totalLiquidity.usd` only works with DUSD, USDT, USDC or DFI pairs. 
#### Why is this needed:
To be able to provide a more accurate value for USD. Another thing that is incorrect also for `getTotalLiquidityUsd`, is it assumes that stablecoins are always $1.

https://github.com/JellyfishSDK/jellyfish/blob/4048de6159246a437c8e3823b1e93cad9a576dbd/apps/whale-api/src/module.api/poolpair.service.ts#L77

**Comment by fuxingloh** [comment]
https://github.com/JellyfishSDK/jellyfish/blob/4048de6159246a437c8e3823b1e93cad9a576dbd/apps/whale-api/src/module.api/poolpair.service.ts#L73-L75

Ideally, we should use a vertex-directed graph to calculate with a maximum of one hop.
